DECLARE 
CURSOR C_EMP IS -- 107 REGISTROS
SELECT EMPLOYEE_ID, SALARY SALARIO, JOB_ID, HIRE_DATE
FROM EMPLOYEES;
--

--
BEGIN
--ABRIR

-- EN UN CICLO CARGAR DATOS EN VARIABLES
FOR REC_EMP IN C_EMP LOOP;

--PROCESAMIENTO

DBMS_OUTPUT.PUT_LINE (LPAD(C_EMP%ROWCOUNT,5,'')||' '||REC_EMP.EMPLOYEE_ID || ' CON SALARIO ' ||
					REC_EMP.SALARIO || ' INGREO A LA EMPRESA EL ' ||
					REC_EMP.HIRE_DATE || ' EN EL CARGO DE ' ||
					REC_EMP.JOB_ID);
END LOOP;-- CERRAR
--
-- ETC.
--
END;
/