DECLARE
/*
ESTE ES UN EJEMPLO DE COMENTARIO OCUPANDO MAS DE UNA LINEA
*/
MI_ID              NUMBER:= :CEDULA; -- ID DEL EMPLEADO
MI_SALBASICO       NUMBER:= 1; -- CODIGO DDEL CONCEPTO
MI_SALBASICO_VALOR NUMBER:= 0; -- VALOR DEL CONCEPTO
MI_DIASLABORADOS   NUMBER:= 0; -- DIAS LABORADOS
MIS_ANIOS   NUMBER:= 0; -- ANIOS LABORADOS A LA FECHA
MI_ANTIGUEDAD      NUMBER:= 0; -- VALOR PRIMA POR ANTIGUEDAD
MI_JEFATURA   NUMBER:= 0;  -- VALOR PRIMA POR JEFATURA
EL_SALARIO NUMBER :=0; -- EL SALARIO ASIGNADO
MI_PRIMA  NUMBER:=0; --
MI_AA NUMBER:=0; --
MI_AT NUMBER:=0; --
MI_DEVENGADO NUMBER :=0;
FUNCTION TRAER_ANIOS(PID NUMBER) RETURN NUMBER
IS
MI_RETORNO NUMBER:=0;
BEGIN
SELECT YEARS INTO MI_RETORNO
FROM JOB_YEARS
WHERE EMPLOYEE_ID= PID;
RETURN MI_RETORNO;
END;
--
--
FUNCTION TRAER_DIAS(PID NUMBER) RETURN NUMBER
IS
MI_RETORNO NUMBER:=0;
BEGIN
SELECT NUM_DAYS INTO MI_RETORNO
FROM NUM_DAYS
WHERE EMPLOYEE_ID= PID;
RETURN MI_RETORNO;
END;
--
FUNCTION TRAER_SALARIO(PID NUMBER) RETURN NUMBER
IS
MI_RETORNO NUMBER:=0;
BEGIN
SELECT SALARY INTO MI_RETORNO
FROM EMPLOYEES
WHERE EMPLOYEE_ID= PID;
RETURN MI_RETORNO;
END;
--
FUNCTION SOY_JEFE(PID NUMBER) RETURN NUMBER
IS
MI_RETORNO NUMBER := 0;
BEGIN
BEGIN
SELECT 1 INTO MI_RETORNO
FROM EMPLOYEES E, JOBS J
WHERE E.EMPLOYEE_ID = PID
AND (E.JOB_ID LIKE '%MGR%'
OR E.JOB_ID LIKE '%MAN%')
AND E.JOB_ID = J.JOB_ID;
EXCEPTION
WHEN NO_DATA_FOUND THEN MI_RETORNO := 0;
END;
RETURN MI_RETORNO;
END;
--
-- SECCION EJECUTABLE
--
BEGIN
--
DELETE FROM PAYROLL;
--
EL_SALARIO := TRAER_SALARIO(MI_ID);
MI_DIASLABORADOS:= TRAER_DIAS(MI_ID);
/*
Salario Basico
1 Salario Basico = (Salary/30)*NumDias
*/
SELECT (SALARY/TRAER_PARAMETRO('DM',1))*NUM_DAYS INTO MI_SALBASICO_VALOR
FROM EMPLOYEES E, NUM_DAYS D
WHERE E.EMPLOYEE_ID= D.EMPLOYEE_ID
AND E.EMPLOYEE_ID = MI_ID;
--
INSERT INTO PAYROLL (EMPLOYEE_ID, PYD, PYD_VALUE)
VALUES (MI_ID,MI_SALBASICO,MI_SALBASICO_VALOR);
--
/*
Prima de antiguedad
2 Prima de antiguedad= Si antiguedad entre 0 y 10  ==> 10% del codigo 1
Si antiguedad entre 11 y 20 ==> 15% del codigo 1
En los demas casos 20% del codigo 1
*/
MIS_ANIOS:= TRAER_ANIOS(MI_ID);
IF MIS_ANIOS BETWEEN 0 AND 10 THEN MI_ANTIGUEDAD := MI_SALBASICO_VALOR*0.1;
ELSIF MIS_ANIOS BETWEEN 11 AND 20 THEN MI_ANTIGUEDAD := MI_SALBASICO_VALOR*0.15;
ELSE
MI_ANTIGUEDAD := MI_SALBASICO_VALOR*0.20;
END IF;
--
INSERT INTO PAYROLL (EMPLOYEE_ID, PYD, PYD_VALUE)
VALUES (MI_ID,2,MI_ANTIGUEDAD);
--
/*
Prima de servicios por jefatura
3 Prima de servicios=  Si cargo es jefe, el 20% del codigo 1
En los demas casos, no hay prima
*/
IF SOY_JEFE(MI_ID) = 1 THEN
MI_PRIMA := MI_SALBASICO_VALOR*0.20;
INSERT INTO PAYROLL (EMPLOYEE_ID, PYD, PYD_VALUE)
VALUES (MI_ID,3,MI_PRIMA);
--
END IF;
    --
/*
Subsidio de alimentacion
4 Subsidio de alimentacion= Si asignacion mensual < 3000 ==> SA= (100/30)* NumDias
 En los demas caso, no hay auxilio

*/
IF EL_SALARIO < TRAER_PARAMETRO('AA',2) THEN
MI_AA:=(TRAER_PARAMETRO('AA',2)/TRAER_PARAMETRO('DM',1))*MI_DIASLABORADOS;
        INSERT INTO PAYROLL (EMPLOYEE_ID, PYD, PYD_VALUE)
VALUES (MI_ID,4,MI_AA);
END IF;
--
/*
5 Subsidio de transporte= Si asignacion mensual < 3000 ==> ST=(80/30)*NumDias
En los demas casos no hay auxilio
*/
    --
IF EL_SALARIO < TRAER_PARAMETRO('AT',2) THEN
MI_AT:=(TRAER_PARAMETRO('AT',2)/TRAER_PARAMETRO('DM',1))*MI_DIASLABORADOS;
        INSERT INTO PAYROLL (EMPLOYEE_ID, PYD, PYD_VALUE)
VALUES (MI_ID,5,MI_AA);
END IF;
    --
/*
10 Total devengado= Suma de los codigo 1-9
*/
MI_DEVENGADO := MI_AA+MI_AA+MI_SALBASICO_VALOR+MI_PRIMA;
INSERT INTO PAYROLL (EMPLOYEE_ID, PYD, PYD_VALUE)
VALUES (MI_ID,10,MI_DEVENGADO);
--
COMMIT;
END;
/