DECLARE 
CURSOR C_EMP IS -- 107 REGISTROS
SELECT EMPLOYEE_ID, SALARY SALARIO, JOB_ID, HIRE_DATE
FROM EMPLOYEES;
--
REC_EMP C_EMP%ROWTYPE;
--
BEGIN
--ABRIR
OPEN C_EMP;

-- EN UN CICLO CARGAR DATOS EN VARIABLES
FETCH C_EMP INTO REC_EMP;
WHILE C_EMP%FOUND LOOP
--PROCESAMIENTO

DBMS_OUTPUT.PUT_LINE (LPAD(C_EMP%ROWCOUNT,5,'')||' '||REC_EMP.EMPLOYEE_ID || ' CON SALARIO ' ||
					REC_EMP.SALARIO || ' INGREO A LA EMPRESA EL ' ||
					REC_EMP.HIRE_DATE || ' EN EL CARGO DE ' ||
					REC_EMP.JOB_ID);
					
FETCH C_EMP INTO REC_EMP;
END LOOP;-- CERRAR
CLOSE C_EMP;
--
-- ETC.
--
END;
/